// tools/beats.mjs: analyse a music track so shots can land on its beats.
//   node tools/beats.mjs assets/audio/song.mp3 [--min=70] [--max=180] [--bpm=<exact, skips the estimate>] [--out=src/beats.js]
// Writes window.BEATS = { bpm, offset, onsets, bars } where offset is the time of beat 0, onsets are strong
// transients (hits worth animating) and bars holds loudness per bar (find the drop and the quiet intro).
// The estimate is good for steady pop, electronic and rock tracks; check it by ear in the preview and nudge
// offset or bpm by hand if the bounce drifts.
import { spawnSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const file = process.argv[2];
const opt = Object.fromEntries(process.argv.slice(3).map(a => { const [k, v] = a.replace(/^--/, '').split('='); return [k, v]; }));
if (!file) { console.error('usage: node tools/beats.mjs <audio file> [--min=70 --max=180 --out=src/beats.js]'); process.exit(1); }
const SR = 22050, FRAME = 1024, HOP = 512, hopT = HOP / SR;
const r = spawnSync('ffmpeg', ['-v', 'error', '-i', file, '-ac', '1', '-ar', String(SR), '-f', 'f32le', '-'], { maxBuffer: 1 << 30 });
if (r.status) { console.error(String(r.stderr)); process.exit(1); }
const raw = Buffer.from(r.stdout), x = new Float32Array(raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.length - raw.length % 4));
const dur = x.length / SR, nF = Math.floor((x.length - FRAME) / HOP);

// Onset strength: rise in log energy of the full signal and of its first difference (which favours transients).
const e1 = new Float64Array(nF), e2 = new Float64Array(nF);
for (let f = 0; f < nF; f++) {
  let a = 0, b = 0; const o = f * HOP;
  for (let i = 1; i < FRAME; i++) { const s = x[o + i], d = s - x[o + i - 1]; a += s * s; b += d * d; }
  e1[f] = Math.log(a + 1e-9); e2[f] = Math.log(b + 1e-9);
}
let on = new Float64Array(nF);
for (let f = 1; f < nF; f++) on[f] = Math.max(0, e1[f] - e1[f - 1]) + Math.max(0, e2[f] - e2[f - 1]);
const loc = new Float64Array(nF);   // subtract a local mean so sustained loud parts do not dominate
for (let f = 0; f < nF; f++) { let s = 0, c = 0; for (let k = Math.max(0, f - 8); k <= Math.min(nF - 1, f + 8); k++) { s += on[k]; c++; } loc[f] = Math.max(0, on[f] - s / c); }
on = loc;

// Tempo: autocorrelation over the allowed BPM range, weighted towards 120 to avoid octave errors.
const minB = +(opt.min || 70), maxB = +(opt.max || 180);
let best = { s: -1, lag: 0 };
const ac = lag => { let s = 0; for (let f = 0; f + lag < nF; f++) s += on[f] * on[f + lag]; return s / (nF - lag); };
for (let lag = Math.floor(60 / (maxB * hopT)); lag <= Math.ceil(60 / (minB * hopT)); lag++) {
  const bpm = 60 / (lag * hopT), w = Math.exp(-.5 * Math.pow(Math.log2(bpm / 120), 2)), s = ac(lag) * w;
  if (s > best.s) best = { s, lag };
}
const [y0, y1, y2] = [ac(best.lag - 1), ac(best.lag), ac(best.lag + 1)], den = y0 - 2 * y1 + y2;
// --bpm=<exact> skips the estimate: autocorrelation can be ~0.4 BPM off ("Dans le club": 115.4 for a true 115.0),
// which drifts a full beat over a minute. Measure it from two repeats of the chorus (their offset is whole bars).
const lag = opt.bpm ? 60 / (+opt.bpm * hopT) : best.lag + (den ? .5 * (y0 - y2) / den : 0), bpm = 60 / (lag * hopT);

// Phase: the offset whose beat grid collects the most onset strength.
let bestP = { s: -1, p: 0 };
for (let p = 0; p < lag; p++) { let s = 0; for (let k = p; k < nF; k += lag) s += on[Math.round(k)] || 0; if (s > bestP.s) bestP = { s, p }; }
const offset = +(bestP.p * hopT + FRAME / 2 / SR).toFixed(3);

// Strong onsets: local peaks above mean + 1.5 sd, at least 100 ms apart.
const mean = on.reduce((a, b) => a + b, 0) / nF, sd = Math.sqrt(on.reduce((a, b) => a + (b - mean) ** 2, 0) / nF);
const onsets = []; let last = -1;
for (let f = 1; f < nF - 1; f++) {
  const t = f * hopT;
  if (on[f] > mean + 1.5 * sd && on[f] >= on[f - 1] && on[f] >= on[f + 1] && t - last > .1) { onsets.push(+t.toFixed(3)); last = t; }
}

// Loudness per bar (4 beats), normalised 0..1.
const barLen = 4 * 60 / bpm, bars = [];
for (let t = offset; t < dur; t += barLen) {
  const a = Math.floor(t * SR), b = Math.min(x.length, Math.floor((t + barLen) * SR)); let s = 0;
  for (let i = a; i < b; i++) s += x[i] * x[i];
  bars.push({ t: +t.toFixed(3), rms: Math.sqrt(s / Math.max(1, b - a)) });
}
const peak = Math.max(...bars.map(b => b.rms)) || 1;
bars.forEach(b => b.rms = +(b.rms / peak).toFixed(3));

const out = opt.out || 'src/beats.js';
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// generated by tools/beats.mjs from ${file}\nwindow.BEATS = ${JSON.stringify({ file, duration: +dur.toFixed(3), bpm: +bpm.toFixed(2), offset, onsets: onsets.slice(0, 4000), bars })};\n`);
console.log(`${file}: ${dur.toFixed(1)} s, ${bpm.toFixed(1)} BPM, beat 0 at ${offset}s, ${onsets.length} onsets, ${bars.length} bars → ${out}`);
const loud = bars.map((b, i) => [i, b.rms]).sort((a, b) => b[1] - a[1]).slice(0, 4).map(([i]) => bars[i].t).sort((a, b) => a - b);
console.log('loudest bars start at: ' + loud.join('s, ') + 's');
